# colorscheme lucius
# colorscheme tomorrow-night
colorscheme black-on-white

add-highlighter global/ number-lines -relative -hlcursor
# add-highlighter global/ number-lines -hlcursor
add-highlighter global/ show-matching
#add-highlighter global/ column 80 StatusLine
add-highlighter global/ column 80 MenuBackground

set-option global ui_options terminal_assistant=none
#set-option global scrolloff 5,5
set-option global autoreload yes


# kak-lsp
#if [ -x "$(command -v kak-lsp)" ]; then
  # enable kakoune lsp
  eval %sh{kak-lsp}
  hook global WinSetOption filetype=(rust|python|go|javascript|typescript|c|cpp) %{
    lsp-enable-window
  }

  # key mappings
  map global user l ':enter-user-mode lsp<ret>' -docstring 'LSP mode'

  map global insert <tab> '<a-;>:try lsp-snippets-select-next-placeholders catch %{ execute-keys -with-hooks <lt>tab> }<ret>' -docstring 'Select next snippet placeholder'

  map global object a '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
  map global object <a-a> '<a-semicolon>lsp-object<ret>' -docstring 'LSP any symbol'
  map global object f '<a-semicolon>lsp-object Function Method<ret>' -docstring 'LSP function or method'
  map global object t '<a-semicolon>lsp-object Class Interface Struct<ret>' -docstring 'LSP class interface or struct'
  map global object d '<a-semicolon>lsp-diagnostic-object --include-warnings<ret>' -docstring 'LSP errors and warnings'
  map global object D '<a-semicolon>lsp-diagnostic-object<ret>' -docstring 'LSP errors'

  #set global lsp_debug true

#fi

add-highlighter global/git-diff flag-lines Default git_diff_flags

hook global -group git-gutter-hooks BufCreate .* %{
  try %{ git show-diff }
}
hook global -group git-gutter-hooks FocusIn .* %{
  try %{ git-async update-diff-via-git }
}
hook global -group git-gutter-hooks BufReload .* %{
  try %{ git-async update-diff-via-git }
}
hook global -group git-gutter-hooks BufWritePost .* %{
  try %{ git-async update-diff-via-git }
}
hook global -group git-gutter-hooks NormalIdle .* %{
  try %{ git-async update-diff-via-git }
}
